REM INSERTING into SAPIENS.BBDD
SET DEFINE OFF;
Insert into SAPIENS.BBDD (COD_PROYECTO,NOM_BBDD,NOM_ESQUEMA,NOM_BBDD_HIS,NOM_ESQUEMA_HIS,MCA_DEFECTO,PASSWORD) values ('SMD','HR','HR','HR','HR','N','hr1');
Insert into SAPIENS.BBDD (COD_PROYECTO,NOM_BBDD,NOM_ESQUEMA,NOM_BBDD_HIS,NOM_ESQUEMA_HIS,MCA_DEFECTO,PASSWORD) values ('PROY1','BD1','ESQUEMA1','BBDD0','ESQUEMA0','S','PROY1');
Insert into SAPIENS.BBDD (COD_PROYECTO,NOM_BBDD,NOM_ESQUEMA,NOM_BBDD_HIS,NOM_ESQUEMA_HIS,MCA_DEFECTO,PASSWORD) values ('PROY1','BD2','ESQUEMA2','BBDD0','ESQUEMA0','S','PROY1');
