REM INSERTING into SAPIENS.OBJ_HIS
SET DEFINE OFF;
Insert into SAPIENS.OBJ_HIS (COD_PROYECTO,LINEA,NOM_OBJETO,TIP_OBJETO,MCA_VIG,MCA_HIS) values ('SMD',null,'AAA','TABLA','S','N');
Insert into SAPIENS.OBJ_HIS (COD_PROYECTO,LINEA,NOM_OBJETO,TIP_OBJETO,MCA_VIG,MCA_HIS) values ('SMD',null,'BBB','TABLA','S','N');
Insert into SAPIENS.OBJ_HIS (COD_PROYECTO,LINEA,NOM_OBJETO,TIP_OBJETO,MCA_VIG,MCA_HIS) values ('SMD',null,'CCC','TABLA','S','N');
Insert into SAPIENS.OBJ_HIS (COD_PROYECTO,LINEA,NOM_OBJETO,TIP_OBJETO,MCA_VIG,MCA_HIS) values ('SMD',null,'DDD','TABLA','S','S');
Insert into SAPIENS.OBJ_HIS (COD_PROYECTO,LINEA,NOM_OBJETO,TIP_OBJETO,MCA_VIG,MCA_HIS) values ('SMD',null,'EEE','TABLA','S','S');
