REM INSERTING into SAPIENS.SUBPROYECTO
SET DEFINE OFF;
Insert into SAPIENS.SUBPROYECTO (COD_PROYECTO,COD_SUB_PROY,DES_SUB_PROY,COD_USR,FEC_ACTU) values ('SMD','SUB_SMD_LD_FD012','SUB_SMD_LD_FD012',null,null);
Insert into SAPIENS.SUBPROYECTO (COD_PROYECTO,COD_SUB_PROY,DES_SUB_PROY,COD_USR,FEC_ACTU) values ('PROY1','SUBPROY1','SUBPROYECTO 1 CON NOMBRE MUY MUY MUY MUY MUY MUY LARGO',null,null);
