SET DEFINE ON
SET VERIFY ON
SET ECHO OFF
SPOOL "/home/federico/SQL/SMD_BORRADO_Tabla_A.sql.log"
DEFINE DAT_SMD_LD_U64K=DAT_SMD_LD_U64K
DEFINE IND_SMD_LD_U64K=IND_SMD_LD_U64K
DEFINE USROWN=HR
@"/home/federico/SQL/SMD_BORRADO_Tabla_A.sql"
SPOOL OFF
EXIT
